### ISSUE TITLE
Try to validate goodness of Jakarta-RS providers for 2.13

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-jakarta-rs-providers#1]
This is sort of a meta-task to gather information on what works and (more importantly) what does not, wrt whole JAX-x / Jakarta-x migration.

Users SHOULD be able to use Jakarta-rs (jakarta.ws.rs) Providers from this repo, over JAX-RS variants from https://github.com/FasterXML/jackson-jaxrs-providers -- and this includes use of new Jakarta variants of XML Bind annotations, which come from here:

https://github.com/FasterXML/jackson-modules-base/tree/master/jakarta-xmlbind

But right now I suspect even "may be able to" is an overstatement. So I am looking for help in validating this approach.

**Comment by cowtowncoder** [comment]
@GedMarc as per above, do you think you could poke providers, see what kind of issues I have missed? :)

**Comment by GedMarc** [comment]
On it sir!

**Comment by cowtowncoder** [comment]
Excellent!

**Comment by cowtowncoder** [comment]
Hi @GedMarc -- have had any time to see how things work (or do not)?

**Comment by GedMarc** [comment]
hey, yeah I have / just haven't gotten round to testing on the cxf 3.4.4 release (two days ago) just yet, 

it looks good so far, let me do one final run through, back in 10

**Comment by cowtowncoder** [comment]
Np; I have been swamped with things so no hurry. But wanted to see if there are specific findings, things I forgot etc.

Also looks like only one JAX/Jakarta-RS provider (Jersey) has fully migrated (has a new version for Jakarta stuff)?
Although others are looking for various approaches. But that's fine, I think we mostly need one for testing.

**Comment by GedMarc** [comment]
So far tomat and jersey yeah, 

oh are you leaving the module-info inside the versions/11 folder? 
Think I've found something just going to make a quick fork and make sure

**Comment by cowtowncoder** [comment]
I have no strong opinion on versions/11 or alternatives, open to suggestions. Esp. since these are "new" modules.

**Comment by cowtowncoder** [comment]
Merged suggested changes so I hope we are closer to good state here?

**Comment by cowtowncoder** [comment]
Since 2.13.0 is now released we might get some actual Beta testing; closing this issue.
