### ISSUE TITLE
licenses missing from jars

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-jakarta-rs-providers#14]
Unlike other jackson projects, none of the modules have META-INF/LICENSE files added to the jars.

**Comment by cowtowncoder** [comment]
Right, I added missing NOTICE and LICENSEs the other day on format modules and jackson-jr.
I think most repos had them at some point but they were sometimes dropped when consolidating. And in this case probably just not copied over when cloning jaxrs-providers repo.

**Comment by cowtowncoder** [comment]
Fixed via #15.
