### ISSUE TITLE
Missing JacksonJaxbJson provider?

### ISSUE THREAD

**Issue by davidvuckovic** [FasterXML/jackson-jakarta-rs-providers#17]
https://github.com/FasterXML/jackson-jaxrs-providers/blob/2.14/json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJaxbJsonProvider.java

The javax one seems to have this. Is this intentional?

**Comment by manmedia** [comment]
Hi @davidvuckovic - you closed this issue - but did not report what the solution was. Some of us are having problems identifying what this could be.

Would you please share?

**Comment by cowtowncoder** [comment]
It is also unclear what the reported problem is, fwtw.
