### ISSUE TITLE
release v2.16.1 seems incomplete

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-jakarta-rs-providers#25]
I've just logged into https://oss.sonatype.org/ and there is unreleased 'staging repository' for this module.

I'm not sure if this is still WIP but I'm just raising this just in case there was an oversight.

**Comment by cowtowncoder** [comment]
@pjfanning Ugh. Thank you for spotting this -- it was the last repo to release and I had forgotten to release it via UI.
Done now.
