### ISSUE TITLE
logback dependency

### ISSUE THREAD

**Issue by pvarga88** [FasterXML/jackson-jakarta-rs-providers#5]
There seems to be an implementation dependency on logback:

This creates a conflict for projects using slf4j with log4j2. I just excluded it but I don't think I should have to.

+--- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider:2.13.0-rc1
|    +--- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-base:2.13.0-rc1
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.0-rc1 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.0-rc1 (*)
|    |    +--- ch.qos.logback:logback-classic:1.2.3
|    |    |    +--- ch.qos.logback:logback-core:1.2.3
|    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.31
|    |    \--- com.fasterxml.jackson:jackson-bom:2.13.0-rc1 (*)
|    +--- com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:2.13.0-rc1
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.0-rc1 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.0-rc1 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.0-rc1 (*)
|    |    +--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1
|    |    |    \--- com.sun.activation:jakarta.activation:2.0.1
|    |    +--- jakarta.activation:jakarta.activation-api:1.2.1
|    |    \--- com.fasterxml.jackson:jackson-bom:2.13.0-rc1 (*)
|    +--- ch.qos.logback:logback-classic:1.2.3 (*)
|    \--- com.fasterxml.jackson:jackson-bom:2.13.0-rc1 (*)

**Comment by cowtowncoder** [comment]
D'oh.

Yes, this definitely needs to be `test` dependency, not compile. Thank you for reporting it!
